# Generated by Django 4.2 on 2023-04-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
