# Generated by Django 4.2 on 2023-04-21 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kafe', '0006_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('created', 'name'), 'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
    ]
